//! Documentation as project state: the crate that keeps `SPEC.md` §9's promise that
//! implementation drift shows up as a red `tm docs check`, not as a README that has quietly
//! been wrong for eleven months.
//!
//! A doc is a project object with a declared basis: `derived_from` names the source globs,
//! [`tm_types::DecisionId`]s and config files it was written from ([`registry`]). That basis is
//! compiled into matchers so a set of changed paths or superseded decisions can be resolved back
//! to the docs they touch ([`provenance`]). [`assess::Assessor::assess`] is the staleness state
//! machine run after every commit/index update: it moves touched docs from `Fresh` to `Stale`,
//! emits `doc.invalidated`, honours explicit human dismissals, and — because it owns the doc
//! registry across calls — never re-invalidates a doc that is already `Stale`. `tm docs check`
//! is [`assess::Assessor::check`]: a non-empty `Stale` set is a hard failure, not advice.
//!
//! [`reconcile`] is where the hard rule lives, enforced as code rather than as intent: a
//! `Generated` doc may be regenerated by the system, but a `Maintained` or `Human` doc can only
//! ever receive a review ticket that a human closes with an attestation. Attempting to rewrite a
//! `Human` doc through this crate is a hard [`tm_types::TmError::AuthorityDenied`], not a lint.
//!
//! Every module here is pure logic over injected state; nothing reads the wall clock or files
//! directly — discovery and persistence are the caller's job (`tm-core`'s `docs`/`doc_provenance`
//! tables, `tm-codeintel`'s repo walk), timestamps and ids come from an injected
//! [`tm_types::Clock`]/[`tm_types::IdSource`]. See `SPEC.md` §9.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

/// Doc discovery and parsing: front matter, the `.tmdocs.toml` fallback, [`registry::DocRecord`]
/// and the registry that lists and registers docs.
pub mod registry;

/// Provenance compilation and matching: `derived_from` entries to path matchers and decision
/// references, and the answer to "which docs does this change touch".
pub mod provenance;

/// The staleness state machine: `assess(changes) -> Vec<DocAssessment>` and the `tm docs check`
/// exit gate.
pub mod assess;

/// Reconciliation: regeneration tickets for `Generated` docs, review tickets and attestations for
/// `Maintained`/`Human` docs, and the hard refusal to rewrite a `Human` doc.
pub mod reconcile;

pub use assess::{Assessor, Dismissal, DocAssessment};
pub use provenance::{ChangeSet, CompiledProvenance, ProvenanceIndex};
pub use reconcile::{Attestation, ReconcileError, ReconciliationKind, ReconciliationTicket};
pub use registry::{
    DocFrontMatter, DocMode, DocRecord, DocRegistry, DocState, DocTomlEntry, TmDocsToml,
};
